# .gitpod.yml

image:
  file: .gitpod.Dockerfile # Verwendet ein benutzerdefiniertes Dockerfile

tasks:
  - name: Install Dependencies and Prepare Environment
    init: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      # Installiere die korrekte TTS-Bibliothek und Test-Abhängigkeiten
      pip install TTS==0.22.0 pytest pytest-cov soundfile
      # Akzeptiere die Coqui TTS-Lizenzbedingungen vorab, indem das Modell heruntergeladen wird.
      # 'yes' beantwortet die Lizenzabfrage automatisch mit 'y'.
      yes | tts --model_name "tts_models/multilingual/multi-dataset/xtts_v2" --text "test" --out_path "/tmp/test.wav" && rm "/tmp/test.wav"
    command: |
      source venv/bin/activate
      echo "==== Führe Projekt-Validierung (Tests) aus ===="
      pytest
      echo "================================================"
      echo ""
      echo "✅ GitPod-Umgebung für Testvoice ist bereit."
      echo "   Führen Sie 'python gui.py' aus, um die Anwendung zu starten."

ports:
  - port: 8000 # Beispiel-Port, falls Sie eine Web-UI oder API starten
    onOpen: ignore # Ignoriert das automatische Öffnen des Ports im Browser